import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Header from 'components/Header';
import { useElementOnScreen } from 'helpers/useElementOnScreen';

function MyApp({ Component, pageProps }: AppProps) {
  const [sentinelRef, isVisible] = useElementOnScreen({ threshold: 0.2 });

  return (
    <div>
      <Head>
        <title>Intersection Observer API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header smallHeading={!isVisible} />
      <main className="p-4 pt-20 min-h-screen relative">
        <div className="w-full h-[90px] bg-slate-400 mb-2" ref={sentinelRef}></div>
        <div>
          <Component {...pageProps} />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}

export default MyApp;
