import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Header from 'components/Header';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div>
      <Head>
        <title>Intersection Observer API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="mt-[90px] p-4 pt-20 min-h-screen">
        <div className="w-[900px] m-auto max-w-full">
          <Component {...pageProps} />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}

export default MyApp;
